### ISSUE TITLE
THIS IS A SCAM.

### ISSUE THREAD

**Issue by TheAlmightyCurd** [dodinhhoanganh/PCS5#1]

**Comment by dodinhhoanganh** [comment]
Oh! This is not a scam, Im just try to make PS5 Emulator and this emulator is in working. FYK, it now can extract PUP File but not decrypt yet! and I will try to extract encrypt PUP File! After that I will find the way to boot elf file inside firmware.
Thank you for take care of this emulator!
And this emu is not for user yet!
